language: node_js
repo_token: h21fzBMVb7OhMqKBwlAtW7uynWrUO7LCY
node_js:
- 5
before_script:
- npm run mocha
- npm run cov
script: npm run deploy
after_success: "< coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
before_deploy: echo 'deploy start'
deploy:
  provider: heroku
  api_key:
    secure: HDuXDVfJkSTFi53uC/gzW7Rvyt+kJKwF1W3Jtb1RAqb4VHxmyAdwIsK2lnJ/4aRZlVVZMVPcM7id3xteahurwqRLz03U70S7XwZkrwaQ4iUqqzzX9gDUakiDx9Ob8zfDDY/LjqKwjJwRKTY6czvazHf2m6KVX/MeA5LSdKuQY+AeHaj0MTaZVFgkcKnskKLQ8QnKVHnucGGl7JMrb7OFkBmdJNu3jqPkdMtRr2eWf6lBJQdoKmEldkyHeTXdmRR+efILP8g/XlnqeuvAWMTX4KvL5VMTUXO3eJj0Ms8QyIG9Qm5lCQcqyw3w5sfcPfYqePsgHkanT2sJNKP2zHYC319/jBmzw689QGjNg5DF44a+U+HBpM9OJ4XQ7R0zC+YIpqZWhG4C1t8W+YOFaV5mRLXwoq3g1QiHh88bozEJqwnlnTB6fYuTbC++mdDhhmlWRC1FBlrEkS6F3RxbGPanlvLgwhLSvGp2Dk+GwK6jNNFch0gGDszVh/Jc8tFJ4nQhpKA4by7d9U4gdiw4548sXzuTePyO191K9U3z/5Rd9lkiICN4ZplN1VscHaJQu0hm8C1Hg84n8RljMfDNC9LmafoWUziWnNBzE1WcEbLJYqIWHodxOoD4JzN8xvfvJ83BLjimsDbICW1JdaHh8f5TuvbT7vfMktFeY7AShkRyU0g=
  app: cddemo
  on:
    repo: baoyouwangning/cd_demo
after_deploy: echo 'deploy success'