language: node_js
repo_token: h21fzBMVb7OhMqKBwlAtW7uynWrUO7LCY
#services: mongodb
node_js:
  - 5
before_script:
  - 'npm run mocha'
  - 'npm run cov'
script: 'npm run deploy'
after_script:

after_success: "< coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"